{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tdx-device-plugin.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "tdx-device-plugin.labels" . | nindent 4 }}
{{- end -}}
